# Generated by Django 4.2.11 on 2024-06-13 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email_customer",
            field=models.EmailField(max_length=100),
        ),
    ]
