# Generated by Django 4.2.11 on 2024-06-14 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_alter_customer_email_customer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchase", old_name="customer", new_name="id_ticket",
        ),
    ]
